# Generated by Django 4.0.5 on 2022-06-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_theme_scope'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='theme',
            new_name='tag',
        ),
    ]
