# Generated by Django 4.0.5 on 2022-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_date_measurement_date_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date_m',
            field=models.DateField(auto_now_add=True, verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Температура'),
        ),
    ]
