# Generated by Django 4.0.5 on 2022-07-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_sensor_photo_alter_measurement_date_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='photo',
            field=models.ImageField(null=True, upload_to='files/sensors_photos', verbose_name='Фото'),
        ),
    ]
